### ISSUE TITLE
The isssues with get_html_from_doi

### ISSUE THREAD

**Issue by Zhou-openfoam** [olivettigroup/article-downloader#4]
I found, it couldnot  extract full text with the type of .html when I used the get_html_from_doi for springer and wiley, only the abstract obtained. But when I used the  get_pdf_from_doi , the full text with the type .pdf were obtained.  Are there any issues with the get_html_from_doi or other problems?
Thank you.

**Comment by eddotman** [comment]
I've found similar behaviour in the past as well -- I think it may actually be related to how publishers handle access permissions (which appears to be somewhat opaque). Looking at the relevant code for getting Wiley articles:

https://github.com/olivettigroup/article-downloader/blob/master/articledownloader/articledownloader.py#L400-L416

You'll see that you're just requesting the full HTML as you would via the usual web-browsing route. So AFAIK there isn't an obvious solution via this library. :( 

CC @zjensen262 in case you have additional insights
