### ISSUE TITLE
Error while using article downloader

### ISSUE THREAD

**Issue by aman31kmr** [olivettigroup/article-downloader#5]
Hi,

I am getting an error.
C:\ProgramData\Anaconda3\lib\site-packages\articledownloader\articledownloader.py in <module>
      3 import re
      4 import json
----> 5 import scrapers
      6 from autologging import logged, traced
      7 from csv import reader

ModuleNotFoundError: No module named 'scrapers'

I tried installing scraper and scrapers separately. I could not find scrapers anywhere. 

Looking forward to the solution.

**Comment by eddotman** [comment]
This is a result of some old underlying libraries going out of date / having updated versions. Should be fixed now.

cc @zjensen262 @elsaolivetti
