### ISSUE TITLE
Unable to obtain html/pdf files

### ISSUE THREAD

**Issue by spbatchu** [olivettigroup/article-downloader#7]
Hello 

I have tried the following to download a paper: 

import articledownloader
from articledownloader.articledownloader  import ArticleDownloader

downloader = ArticleDownloader(els_api_key='I have used my elsevier API key here')
sample_file=open('firstpdf.pdf','w')
downloader.get_pdf_from_doi('10.1016/j.jbiosc.2010.11.006','sample_file', 'elsevier')
sample_file.close()

In the above piece of code, I have used my elsevier API key. 

The issue is, I am unable to write anything in the file that I have created. I tried writing in HTML format, which did not help too.  I was wondering if there is some issue with the method.

Kindly do the needful.

**Comment by eddotman** [comment]
Couple possibilities come to mind:

1. You may not be running Python with sufficient permissions to write to the file.
2. You've passed the literal string "sample_file" as the second arg to `get_pdf_from_doi()` in your snippet, but you need to pass the pointer to the file. It's not clear to me if that is a typo in your actual code or just the snippet you pasted here.

Please let me know if that helps and if you're able to get things working.

**Comment by Xianjun-Yang** [comment]
Hi Kim, 
When I am using the 'import articledownloader.articledownloader', the mistake is as follows: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-26-1260cc0bd39e> in <module>
----> 1 import articledownloader.articledownloader

~/opt/anaconda3/lib/python3.8/site-packages/articledownloader/articledownloader.py in <module>
      4 import json
      5 from articledownloader import scrapers
----> 6 from autologging import logged, traced
      7 from csv import reader
      8 from time import sleep

ModuleNotFoundError: No module named 'autologging'

Do you know how to solve the problem? (I use pip to install it)

Many thanks!
